version: '3.8'

services:
  my-frontend:
    build:
      context: ./my-frontend
      dockerfile: Dockerfile
      target: dev
    ports:
      - "5173:5173"
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - frontend-network

  app:
    build: .
    container_name: movie-app
    env_file:
      - app/.env
    ports:
      - "5000:5000"
    depends_on:
      - redis
    volumes:
      - .:/app
      # If you need this file inside /app, mount it there instead:
      # - ./hold_seats.lua:/app/hold_seats.lua
    command: ["python", "app/app.py"]
    restart: unless-stopped
    stop_grace_period: 60s

  redis:
    image: redis:7
    container_name: movie-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:

networks:
  frontend-network:
    driver: bridge